

CREATE TABLE `ADMINISTRADOR` (
  `ADM_ID` int(11) NOT NULL,
  `ADM_NOME` varchar(24) NOT NULL,
  `ADM_SENHA` varchar(24) NOT NULL,
  `ADM_ATIVO` varchar(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `CATEGORIA` (
  `CATEGORIA_ID` int(11) NOT NULL,
  `CATEGORIA_NOME` varchar(255) NOT NULL,
  `CATEGORIA_DESC` varchar(255) NOT NULL,
  `CATEGORIA_ATIVO` bit(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `PRODUTO` (
  `PRODUTO_ID` int(11) NOT NULL,
  `PRODUTO_NOME` varchar(255) NOT NULL,
  `PRODUTO_DESC` varchar(500) NOT NULL,
  `PRODUTO_PRECO` decimal(10,2) NOT NULL,
  `PRODUTO_DESCONTO` decimal(10,2) NOT NULL,
  `PRODUTO_ATIVO` bit(1) NOT NULL,
  `CATEGORIA_ID` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE `PRODUTO_ESTOQUE` (
  `PRODUTO_ID` int(11) NOT NULL,
  `PRODUTO_QTD` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

  CREATE TABLE `PRODUTO_IMAGEM` (
    `IMAGEM_ID` int(11) NOT NULL,
    `IMAGEM_URL` varchar(8000) NOT NULL,
    `IMAGEM_ORDEM` int(11) NOT NULL,
    `PRODUTO_ID` int(11) NOT NULL
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE `ADMINISTRADOR`
  ADD PRIMARY KEY (`ADM_ID`);

ALTER TABLE `CATEGORIA`
  ADD PRIMARY KEY (`CATEGORIA_ID`);

ALTER TABLE `PRODUTO`
  ADD PRIMARY KEY (`PRODUTO_ID`);

ALTER TABLE `PRODUTO_IMAGEM`
  ADD PRIMARY KEY (`IMAGEM_ID`);

/* ---------------- */

ALTER TABLE `ADMINISTRADOR`
  MODIFY `ADM_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

ALTER TABLE `CATEGORIA`
  MODIFY `CATEGORIA_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

ALTER TABLE `PRODUTO`
  MODIFY `PRODUTO_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

ALTER TABLE `PRODUTO_IMAGEM`
  MODIFY `IMAGEM_ID` int(11) NOT NULL AUTO_INCREMENT=4;
COMMIT;
